name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Route npm registry through Wix embargo proxy
        uses: wix-actions/packages-firewall@b764ce3431d7830e3c5d5df3470a4cc14f03bca3 # master @ 2026-09-01

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: npx npq@3.27.0 install
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPQ_ALLOW_NON_INTERACTIVE_INSTALL: 'true'
          NPQ_PKG_MGR: yarn

      - name: Verify package
        run: yarn prepack

      - name: Inspect package contents
        run: npm pack --dry-run --ignore-scripts
